version: build {build}

image:
  - Ubuntu

build:
  verbosity: minimal

branches:
  except:
    - gh-pages
skip_tags: true

init:
  - git config --global core.autocrlf input

before_build:
  - dotnet tool restore
  - dotnet nbgv cloud

build_script:
  - export NUGET_PACKAGES="$APPVEYOR_BUILD_FOLDER/.nuget"
  - dotnet paket restore
  - dotnet build -c:release
  - dotnet paket pack ./build --version "$(dotnet nbgv get-version -v SemVer2)"

environment:
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL

# all builds on the AppVeyor NuGet feed
artifacts:
  - path: build\*.nupkg
    name: nuget

cache:
  - .nuget
